### ISSUE TITLE
Linking a model-element to a graphic element in svg

### ISSUE THREAD

**Issue by odungern** [oalt/fmc4seSvgGenerator#1]
@oalt: The other day you have brought up again the question how to specify in SVG a model-element which is represented by a graphical element.

I have thought about it again:
- For ARCWAY Cockpit we have discussed the issue a couple of years ago. We did not want to use the model-element id for the id-attribute value of the graphical element, because multiple representations of the same model-element can appear. So we came up with the idea to add the model-element id as class value. Then we can select and access all graphic elements representing a model-element by script ... e.g. for attaching a click-handler. Such a graphic element looks like
```<g class="com.arcway.cockpit.uniqueelement id_5a489c300000bca80137ee1373c16844">```,
where the first class signifies that the graphic element represents a model-element and the second is it's id. This is not particularly beautiful, but works. This is implemented in the SpecIF Viewer/Editor, so that ARCWAY-generated SVGs are animated: [Dimmer](https://specif.de/apps/view#view=doc;project=ACP-59c8a7730000bca80137509a49b1218b;node=SH-Pln-5a6cdea50000bca80137d6b2d6e8a3a0;import=../examples/Dimmer.specifz).
- SVG 1.x defined attributes like ```xlink:href```, which has been replaced by ```href``` in SVG 2.0. This attribute has different meaning in different tags that can be used within a graphical elements, such as ```<a href="uri">```. Since the browser reaction on all these is defined, it is no good idea to use them for another purpose.
- Finally there is the possibility to define proprietory attributes (as does Inkscape as far as I know). So we could say, for example
```<circle id="myCircle" class="specif-model-element" idref="id_123" cx="0" cy="0" r="5" />```. With a script, all graphic elements representing a model-element can easily be selected by the class and then the idref extracted.

What do you think? Got a better idea?

**Comment by odungern** [comment]
.. your proposal to add a property in a meta-data section is even better. But please add also a special class at group-level <g ...>, so that an easy selection of all graphical elements representing a model-element is possible.

**Comment by oalt** [comment]
Done. Have a look at https://github.com/GfSE/SpecIF/blob/master/documentation/03_SpecIF_Diagram_Exchange.md
